# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mazhar's Blog
email: info@mazharAhmed.me
description: > # this means to ignore newlines until "baseurl:"
  Entrepreneur, Product Enthusiast, Tech Expert, Designer, Brander
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mazharahmed.me" # the base hostname & protocol for your site
twitter_username: mighty_maze
github_username:  mazhar266
site.google_analytics: 'UA-48146313-1'

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /:title

plugins: [jekyll-paginate, jekyll-seo-tag, jemoji]

#theme: jekyll-theme-architect

algolia:
  application_id: 6INW6RZ8ZJ
  index_name: jekyll